# Generated by Django 3.2.13 on 2022-07-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment_form',
            new_name='CommentForm',
        ),
    ]
